### PR TITLE
Disable web page preview for Telegram alerts

### PR DESCRIPTION
**Pull request by evermake**
IMHO web page previews in Telegram alerts take a lot of space but contain no useful information, so it would be better to disable them:

image

### CODE REVIEW

**Comment by MarshalX** [comment]
hi, thanks for your effort. these previews are a historical feature that wasn't disabled for years. at least it promotes my GitHub nickname and reminds me that the project is open-source. Can you suggest an alternative way to promote it?

**Comment by evermake** [comment]
The fact that this is an open-source project and that's you're the author is obvious from the channel description and the pinned message. Moreover, anyone who will open the link to `View diff on GitHub...` will open the repository. Not sure that additional promotions in each post will improve the reputation. 🤷‍♂️

**Comment by MarshalX** [comment]
It's not obvious when someone forwards the post

**Comment by luckydonald** [comment]
I mean even writing the following would take up less space than the link preview:

> ```diff
> -  View diff on GitHub...
> +  Diff: https://github.com/MarshalX/telegram-crawler/commit/a3313a
> ```

**Comment by MarshalX** [comment]
> I mean even writing the following would take up less space than the link preview:
> 
> > ```diff
> > -  View diff on GitHub...
> > +  Diff: https://github.com/MarshalX/telegram-crawler/commit/a3313a
> > ```

lgtm lets apply it

**Comment by evermake** [comment]
@MarshalX, please check it now

**Comment by evermake** [comment]
I also thought to shorten the commit hash in URL, but it's unclear how to do it better, since URL is extracted like this:

```python
html_url = commit_data['html_url']
```

**Comment by MarshalX** [comment]
@evermake the first alert is your version, the second one after my changes 

image

ok?

**Comment by MarshalX** [comment]
thank you

**Pull request merged**
